project_id = "gboskpvfvwrsiqwzpctk"

[functions.woo-sync]
verify_jwt = false

[functions.ezcount-doc]
verify_jwt = false

[functions.woo-stock-update]
verify_jwt = false

[functions.woo-webhook]
verify_jwt = false

[functions.woo-product-sync]
verify_jwt = false

[functions.meta-product-feed]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.order-sms-trigger]
verify_jwt = false

[functions.hyp-create-payment]
verify_jwt = false

[functions.hyp-payment-link]
verify_jwt = false

[functions.migrate-wp-images]
verify_jwt = false

[functions.pay-redirect]
verify_jwt = false

[functions.order-email-notify]
verify_jwt = false

[functions.hyp-verify-payment]
verify_jwt = false

[functions.hyp-notify]
verify_jwt = false

[functions.hyp-callback]
verify_jwt = false

[functions.web-create-order]
verify_jwt = false

[functions.order-summary]
verify_jwt = false

[functions.web-validate-coupon]
verify_jwt = false

[functions.web-best-sellers]
verify_jwt = false

[functions.auto-cancel-pending]
verify_jwt = false

[functions.inv-redirect]
verify_jwt = false
