project_id = "gboskpvfvwrsiqwzpctk"

[functions.woo-sync]
verify_jwt = false

[functions.ezcount-doc]
verify_jwt = false

[functions.woo-stock-update]
verify_jwt = false

[functions.woo-webhook]
verify_jwt = false
